export enum UsersActionTypes {
  GET_ALL_USERS = "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR",

  GET_USER_BY_LOGIN = "GET_USER_BY_LOGIN",
  GET_USER_BY_LOGIN_SUCCESS = "GET_USER_BY_LOGIN_SUCCESS",
  GET_USER_BY_LOGIN_ERROR = "GET_USER_BY_LOGIN_ERROR",
}
